(()=>{const styleBase={position:"fixed",padding:"6px 10px",font:"12px system-ui",borderRadius:"10px",boxShadow:"0 2px 8px rgba(0,0,0,.35)",zIndex:999999,opacity:.95};
function mkBUS(src){if(window.BUS)return;const subs=[];window.BUS={subscribe:f=>{"function"==typeof f&&subs.push(f)},emit:(t,p={},m={})=>{const msg={type:t,payload:p,meta:{...m,ts:Date.now(),src}};subs.forEach(fn=>{try{fn(msg)}catch(_){}});try{window.dispatchEvent(new CustomEvent("BUS",{detail:msg}))}catch(_){ }console.log("[bus:emit]",t,msg);return msg}};console.log("[bus] created ("+src+")")}
function ASAM(x){const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const bin=n=>n>=80?"severe":n>=60?"moderate":n>=40?"mild":"baseline";const base=(x.objectives?.length||0)*10+(x.dx_code?.includes("F33")?25:0);const score=clamp(base,0,100);return{score,level:score>=80?"ASAM 2.5":score>=60?"ASAM 2.1":score>=40?"ASAM 1.0":"Early Intervention",bin:bin(score)}}
function DSM(x){const d=String(x.dx_code||"");return{ctc:d.startsWith("F2")?"CTC-5":d.startsWith("F3")?"CTC-3":d.startsWith("F1")?"CTC-4":"CTC-2",rationale:`mapped from ${d||"unknown"}`}}
function BAND(x){const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const bin=n=>n>=80?"severe":n>=60?"moderate":n>=40?"mild":"baseline";const ac=String(x.phone||"").replace(/\D/g,"").slice(0,3);const flags=[/court|legal/i.test(x.context||"")&&"court-involved",/housing|shelter/i.test(x.context||"")&&"unstable-housing",/relapse/i.test(x.primary_need||"")&&"relapse-risk"].filter(Boolean);const entropy=clamp(flags.length*20+(parseInt(ac||"0",10)%17),0,100);return{area_code:ac||null,flags,entropy,bin:bin(entropy)}}
function VOUCHER(x){let h=0;const s=JSON.stringify(x||{});for(let i=0;i<s.length;i++)h=(h<<5)-h+s.charCodeAt(i),h|=0;h>>>0;const token="VCH-"+(h%1e8).toString().padStart(8,"0");const activation=h%101;return{token,activation,pass:activation>=55,threshold:55}}
document.title="✅ [EMITTER] Pre-Assessment CTC Intake — VSC"; mkBUS("pre-assessment");
if(!window.__AI_WIRED__){window.__AI_WIRED__=!0;BUS.subscribe(m=>{if(m?.type!=="assessment.seed")return;const x=m.payload||{};const txt=[x.primary_need,...(x.objectives||[])].filter(Boolean).join(" ");if(/suicide|kill|harm|overdose/i.test(String(txt||""))){BUS.emit("ai.crisis.detected",{note:"Crisis content detected"});return}const out={asam:ASAM(x),dsm:DSM(x),bandersnatch:BAND(x),eclipse:VOUCHER(x)};BUS.emit("ai.results",out);if(out.eclipse.pass)BUS.emit("ai.voucher.ready",{token:out.eclipse.token});console.log("[ai] results emitted",out)})}
try{window.__PRE_BC__||(window.__PRE_BC__=new BroadcastChannel("preassessment-repo"));BUS.subscribe(m=>{if(!m?.type)return;if(["assessment.seed","consent.signed","ai.results","ai.voucher.ready"].includes(m.type))try{window.__PRE_BC__?.postMessage({type:m.type,payload:m.payload})}catch(e){console.warn("[intake→repo] bc post fail",e)}});console.log("[intake→repo] bridge active")}catch(e){console.warn("[intake→repo] bc unavailable",e)}
document.getElementById("vsc-intake-badge")?.remove();const b=document.createElement("div");b.id="vsc-intake-badge";b.textContent="✅ Pre-Assessment CTC Intake (Emitter)";Object.assign(b.style,{...styleBase,top:"10px",left:"10px",background:"#0b5",color:"#fff"});document.body.appendChild(b);document.documentElement.style.outline="4px solid rgba(0,187,85,.65)";
})();
